export const activityDescriptionPrompts = {
  processing: {
    system: `Extract workout insights from Strava activity data.

Output JSON with:
- workout_type: easy | tempo | intervals | long_run | race | recovery | fartlek | progression
- structure: { warmup_km, main_effort, cooldown_km, repeats?, recovery_duration? }
- paces: { avg_pace, fastest_km, slowest_km, effort_range }
- terrain: { total_elevation, profile: flat | rolling | hilly, surface?: road | trail | track | mixed }
- splits: { pattern: even | negative | positive | fade | variable, notable_splits }
- timing: { time_of_day: morning | afternoon | evening | night, day_of_week }
- social: solo | group | race
- achievements: [] // PRs, milestones, segment placements
- vibe: strong | solid | tough | struggled | cruised // overall feel based on data

Infer workout type from pace variance, duration, and patterns. Be specific with numbers.`,

    user: (data: unknown) => `Extract workout details:\n${JSON.stringify(data, null, 2)}`,
  },

  analysis: {
    system: `Analyze the processed workout data to understand the session story.

Determine:
1. What was the intent? (recovery, base building, speed work, race simulation)
2. Pacing execution - did they nail it, fade, or negative split?
3. Key moments - strong finish, tough middle, fast reps, slow reps
4. Effort vs result - was it harder/easier than the pace suggests?
5. Context clues - weather impact, terrain challenges, time of day fatigue

Output bullet points with specific observations. Max 120 words.`,

    user: (data: unknown) => `What's the story of this workout?\n${JSON.stringify(data, null, 2)}`,
  },

  formatting: {
    system: `Generate a structured workout summary with a descriptive title.

TITLE FORMAT:
[Modifier] [Workout Type] [Context]

Build the title by combining relevant elements:

MODIFIERS (pick one if applicable):
- Terrain: Hilly, Flat, Rolling, Trail, Track
- Execution: Strong, Solid, Tough, Easy, Steady, Fast, Slow
- Pattern: Progressive, Negative Split, Cutdown
- Weather: Hot, Cold, Rainy, Windy
- Special: PR, Race Day, Comeback, First

WORKOUT TYPES:
- Easy Run, Long Run, Tempo, Intervals, Fartlek, Recovery, Race, Progression, Shakeout, Base Run

CONTEXT (pick one if applicable):
- Time: Morning, Afternoon, Evening, Night, Pre-Dawn, Lunchtime
- Purpose: Before Work, After Work, Weekend, Midweek
- Social: Solo, Group, Club, With Pacer

TITLE EXAMPLES:
- "Easy Evening Run"
- "Hilly Long Run"
- "Track Intervals Morning Session"
- "Progressive Tempo"
- "Hot & Humid Base Run"
- "Negative Split Long Run"
- "Rainy Recovery Jog"
- "Strong Finish Progression"
- "Trail Fartlek"
- "Solo Night Run"
- "Flat Fast Tempo"
- "Tough Hilly Intervals"
- "PR Attempt 10K Race"
- "Easy Shakeout Before Race"
- "Windy Threshold Workout"
- "Sunday Long Run"
- "Lunchtime Tempo"
- "Comeback Easy Run"

BODY FORMAT:
[Line 1: Brief workout description]
[Line 2: Structure/intervals detail if applicable]
[Line 3: Pace or effort info]
[Line 4: Terrain/elevation note]
[Line 5: Split pattern observation]
[Line 6: Time of day + solo/group]
[Line 7: Weather/conditions if provided]
[blank line]
⚡ Generated by TempoSync

RULES:
- Title should be 2-4 words, descriptive but not cluttered
- Pick the most distinctive/interesting modifier for the title
- Each body line is a single fact or observation
- No bullet points, dashes, or prefixes
- Short, scannable phrases (not full sentences)
- Specific numbers over vague descriptions
- Output 5-7 body lines total

FULL EXAMPLES:

Hilly Evening Long Run
Weekly long run through the park
24km with 180m elevation gain
First half easy at 5:40/km, finished at 5:15/km
Rolling terrain with two steep climbs
Strong negative split, felt good at the end
Solo evening session after work

⚡ Generated by TempoSync


Track Intervals
6x1km repeats at 10k effort
Fastest rep 4:45/km, slowest 5:12/km
90-second recovery jogs between efforts
Flat track, no elevation
Negative split on final two reps
Solo morning session before work

⚡ Generated by TempoSync


Easy Recovery Jog
Shakeout run, keeping it relaxed
6km at conversational pace
Steady 6:00-6:15/km throughout
Flat neighborhood loop
Even splits, no pushing
Quick afternoon solo spin

⚡ Generated by TempoSync


Rainy Tempo Thursday
Threshold effort despite the weather
5km main block at 4:52/km avg
Flat riverside out-and-back
Even splits with a slight kick at the end
Pushed through light rain and puddles
Solo lunchtime session

⚡ Generated by TempoSync


Progressive Long Run
Building pace over 20km
Started at 5:45/km, finished at 4:55/km
Gradual descent into tempo territory
Mixed terrain, 95m elevation
Textbook negative split execution
Early Sunday morning, cool and quiet

⚡ Generated by TempoSync


Tough Windy Intervals
8x400m on the exposed path
Reps ranged 1:32-1:45, wind was brutal
2-minute standing recovery
Flat but relentless headwind on alternating reps
Struggled on reps 5-6, recovered for final two
Solo evening session

⚡ Generated by TempoSync


Output ONLY the formatted summary, Nothing else.`,

    user: (data: unknown) => {
      const base = JSON.stringify(data, null, 2);

      return `Generate workout summary:\n${base}`;
    },
  },
};
