import { env } from 'cloudflare:workers';

export const {
	API_SECRET,
	CLIENT_ID,
	CLIENT_SECRET,
	COOKIE_SECRET,
	DATABASE_URL,
	GEMINI_API_KEY,
	KEY,
	NODE_ENV,
	REDIRECT_URL,
	REDIRECT_URL_STRAVA,
	SCOPE,
	STRAVA_CLIENT_ID,
	STRAVA_CLIENT_SECRET,
	STRAVA_SCOPE,
	VERIFY_TOKEN,
	WEBHOOK_CALLBACK_URL,
	X_API_KEY,
} = env;
